#!/bin/sh
# XG-040G-MD 自定义配置脚本

# 防火墙硬件加速
uci set firewall.@defaults[0].flow_offloading='1'
uci set firewall.@defaults[0].flow_offloading_hw='1'
uci commit firewall

# conntrack 最大值
echo 300000 > /proc/sys/net/netfilter/nf_conntrack_max

# 系统设置
uci set system.@system[0].timezone='CST-8'
uci set system.@system[0].zonename='Asia/Shanghai'
uci set system.@system[0].hostname='My Wired Router'
uci commit system

# NTP 服务器配置
uci set system.ntp='timeserver'
uci set system.ntp.enabled='1'
uci set system.ntp.enable_server='0'
uci delete system.ntp.server 2>/dev/null
uci add_list system.ntp.server='ntp.aliyun.com'
uci add_list system.ntp.server='ntp.tencent.com'
uci add_list system.ntp.server='time.google.com'
uci add_list system.ntp.server='pool.ntp.org'
uci commit system

# DNS 服务器配置
uci add_list dhcp.@dnsmasq[0].server='223.5.5.5'
uci add_list dhcp.@dnsmasq[0].server='119.29.29.29'
uci commit dhcp

exit 0
